## Initialization

### Initialization

In [24]:
import sys
#sys.path.append('/Users/chandrasekharmukherjee/Home/Centrality framework/Modules')
sys.path.append('I:/내 드라이브/backup/document/USC/Research/MCPC/Code/Codes')

#Import packages
#imports
import time
import pandas as pd
from collections import Counter
import sknetwork


from sknetwork.ranking import PageRank
from sknetwork.ranking import Betweenness
from sknetwork.ranking import Closeness

#import umap as umap

from numba.typed import List
import warnings
from numba import njit
import pynndescent
import numpy as np
from sklearn.cluster import SpectralClustering
import numpy as np
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import matplotlib
import operator
from sklearn.utils.extmath import randomized_svd
from random import randint
from sklearn.utils.extmath import randomized_svd
from sklearn.decomposition import TruncatedSVD
import scipy
#from umap.umap_ import *
import math
from random import randint
import keras
from keras.datasets import mnist
from keras.datasets import cifar10
from keras.datasets import cifar100
from keras.datasets import fashion_mnist
import scanpy
from sklearn.metrics.cluster import normalized_mutual_info_score
from sklearn.metrics import adjusted_mutual_info_score, roc_auc_score
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics.cluster import adjusted_mutual_info_score

#import community as community_louvain
from sklearn.cluster import KMeans
from sklearn.metrics import fowlkes_mallows_score

import scipy

import igraph 
import networkx as nx


import metric as met 
import embedding as embed   
import data_utils_ch as data_util

In [26]:
%load_ext autoreload
%autoreload 2
import importlib

import metric as met 
import embedding as embed   
import data_utils_ch as data_util


met=importlib.reload(met)
embed=importlib.reload(embed)
data_util=importlib.reload(data_util)


hi
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
hi


### Get edge Lists

In [28]:
#This is to get the edge_lists.

#scRNA datasets
datanames=['Zhengmix8eq']
for name in datanames:
    edge_list,vlist,n,label=data_util.local_SCRNA(name)
    print("Dataset names is ",name," |V|, |E| #clusters= ",n,len(edge_list),len(set(label)))


#These are for the bulk-RNA datasets.
datanames=['mRNA','miRNA']
for name in datanames:
    for survive in [0,1]:
        edge_list,vlist,label,n=data_util.local_bulkRNA(name,survive)
        label=data_util.set_labels(label)
        print("Dataset names is ",name," |V|, |E| #clusters= ",n,len(edge_list),len(set(label)))



#These contain image and document data.
#datanames=['FashionMNIST','MNIST','seeds','breast-cancer','Omniglot','bbc_news','20NewsGroups','biorxiv','big_patent']
datanames=['FashionMNIST','MNIST','seeds','breast-cancer','Omniglot','bbc_news','20NewsGroups_tfdif','biorxiv','big_patent']
for name in datanames:
    edge_list, label=data_util.load_data(name,kchoice=10)
    n=len(label)
    vlist=[i for i in range(n)]
    label=data_util.set_labels(label)

    print("Dataset names is ",name," |V|, |E| #clusters= ",n,len(edge_list),len(set(label)))


#These are data of 4 popular directed graphs. 
graphnames=['Cora','Cora full','Citeseer','Eu core']
for name in graphnames:
    edge_list,vlist,label,n,good_v=data_util.graph_database(name)
    label=data_util.set_labels(label)

    print("Dataset names is ",name," |V|, |E| #clusters= ",n,len(edge_list),len(set(label)))

Zhengmix8eq 3994
Log transform done
(3994, 50)
Accuracy of  15 -NN graph is 0.792
59910
Dataset names is  Zhengmix8eq  |V|, |E| #clusters=  3994 59910 8
[0 1 2 3 4 5 6 7 8 9]
(11235, 19939)
selected vertices  11235
(11235,) Counter({'TCGA-BRCA': 1226, 'TCGA-KIRC': 610, 'TCGA-LUAD': 589, 'TCGA-UCEC': 585, 'TCGA-THCA': 572, 'TCGA-HNSC': 566, 'TCGA-PRAD': 554, 'TCGA-LUSC': 552, 'TCGA-LGG': 534, 'TCGA-COAD': 514, 'TCGA-SKCM': 473, 'TCGA-STAD': 448, 'TCGA-OV': 429, 'TCGA-BLCA': 428, 'TCGA-LIHC': 424, 'TCGA-KIRP': 323, 'TCGA-CESC': 309, 'TCGA-SARC': 265, 'TCGA-ESCA': 198, 'TCGA-PCPG': 187, 'TCGA-PAAD': 183, 'TCGA-READ': 177, 'TCGA-GBM': 174, 'TCGA-TGCT': 156, 'TCGA-LAML': 151, 'TCGA-THYM': 122, 'TCGA-KICH': 91, 'TCGA-MESO': 87, 'TCGA-UVM': 80, 'TCGA-ACC': 79, 'TCGA-UCS': 57, 'TCGA-DLBC': 48, 'TCGA-CHOL': 44})
33 32
Dataset names is  mRNA  |V|, |E| #clusters=  11235 168525 33
[ 5  6 10 11 12 14 16 17 25 26]
(9737, 19939)
selected vertices  9737
(9737,) Counter({0: 6980, 1: 2757})
2 1
Dataset 

### Raw Data

In [29]:
#To get the raw data.

#scRNA datasets
datanames=['Zhengmix8eq']
for name in datanames:
    X,n,label=data_util.local_SCRNA(name,raw=1)



#These are for the bulk-RNA datasets.
datanames=['mRNA','miRNA']
for name in datanames:
    for survive in [0,1]:
        X,label,n=data_util.local_bulkRNA(name,survive)
        label=data_util.set_labels(label)



#These contain image and document data.
#datanames=['FashionMNIST','MNIST','seeds','breast-cancer','Omniglot','bbc_news','20NewsGroups','biorxiv','big_patent']
datanames=['FashionMNIST','MNIST','seeds','breast-cancer','Omniglot','bbc_news','biorxiv','big_patent']
for name in datanames:
    X,label=data_util.load_data(name,raw=1)
    n=len(label)
    label=data_util.set_labels(label)






TypeError: local_SCRNA() got an unexpected keyword argument 'raw'

## Testing every dataset with top k % nodes induced subgraph (Louvain)

### Functions for Tok k% induced Subgraph

In [57]:
import FlowRank_General as FR
from sklearn.metrics.cluster import normalized_mutual_info_score as NMI
def getInducedSubgraph(G, k, node2FR): #G = original graph, k = pick top k percent, node2FR = node to FR value
    #Get top k% nodes
    node_list = sorted(G.nodes, key=lambda x: node2FR[x], reverse=True)
    k = int(k*len(node_list))
    top_nodes = node_list[:k]
    #Remove nodes also remove adjacent edges
    H = G.copy()
    for u in G.nodes:
        if u not in top_nodes:
            H.remove_node(u)
    return H

def FlowRank_Func(edge_list,vlist,walk_len_c1,c_const=0,type=0):
    if type==0:
        return FR.FLOW(edge_list,vlist,walk_len_c1,c_const)
    elif type==1:
        return FR.FLOW_ng(edge_list,vlist,walk_len_c1,c_const)
    elif type==2:
        return FR.FLOW_ng_prop(edge_list,vlist,walk_len_c1,c_const)

def calc_FlowRank(graph, FR_type, walk_len_c1):
    node2FR = dict()
    if FR_type==3:
        pg_rank = nx.pagerank(graph,alpha=0.85) #alpha = 0.85 is the default
        node2FR = {k: pg_rank[k]*graph.number_of_nodes() for k in pg_rank}
    else:
        for i in FlowRank_Func(graph.edges(),graph.nodes(),walk_len_c1,0,FR_type):
            node_num = int(i[1])
            node2FR[node_num] = i[0]
    return node2FR

def part_to_label(partition,H,original_n): #partition to labels
    #Mapping node numbers to index
        
    label_1=[-1]*(original_n+1)
    c=0
    for sets in partition:
        for ell in sets:
            label_1[ell]=c
        
        c=c+1
    
    label_compressed = []
    for i in sorted(H.nodes()):
        if label_1[i] == -1: 
            print('Error: Node not found in partition')
            return None
        label_compressed.append([label_1[i]])
    #print(label_compressed)
    return label_compressed

def get_NMI(H, partition, label, original_n):
    #Keep the labels of the nodes in subgraph G only
    new_label = []
    for i in sorted(H.nodes()):
        #print('node: ',i)
        new_label.append(label[i])
    #change the partition form {[node2,node4], [,...,]} to label form {[0,2,1,2,grp#,...]}
    part_label = part_to_label(partition,H, original_n)
    
    arr = np.array(part_label)
    arr = arr.flatten()
    nmi = NMI(arr, new_label)
    return nmi

def get_Purity(H, partition, label, original_n):
    #Keep the labels of the nodes in subgraph G only
    new_label = []
    for i in sorted(H.nodes()):
        #print('node: ',i)
        new_label.append(label[i])
    #change the partition form {[node2,node4], [,...,]} to label form {[0,2,1,2,grp#,...]}
    part_label = part_to_label(partition,H, original_n)
    
    arr = np.array(part_label)
    arr = arr.flatten()
    purity = met.purity_score(arr, new_label)
    return purity

def relabel_graph(H): #compress the node numberings 
    mapping = dict(zip(H.nodes(), range(H.number_of_nodes())))
    H = nx.relabel_nodes(H, mapping)
    return H

def check_if_has_edge(H, partition_):
    for i in H.nodes():
        for j in H.nodes():
            if i!=j and H.has_edge(i,j):
                #find i in partition_
                for k in range(len(partition_)):
                    if i in partition_[k]:
                        if j not in partition_[k]:
                            print('Edge between nodes:',i,j) #Edge between two different communities
    return

# def make_graph(edge_list):
#     G = nx.Graph(edge_list)
#     return G
                                            

### Convert Dataset into a NetworkX Graph

In [56]:
def data_to_graph(name, survive=0):
    #scRNA datasets
    if name in ['Zhengmix8eq']:
        edge_list,vlist,n,label=data_util.local_SCRNA(name)
        #print("Dataset names is ",name," |V|, |E| #clusters= ",n,len(edge_list),len(set(label)))

    #These are for the bulk-RNA datasets.
    elif name in ['mRNA','miRNA']:
        #for survive in [0,1]:
        edge_list,vlist,label,n=data_util.local_bulkRNA(name,survive)
        label=data_util.set_labels(label)
        #print("Dataset names is ",name," |V|, |E| #clusters= ",n,len(edge_list),len(set(label)))

    #These contain image and document data.
    #datanames=['FashionMNIST','MNIST','seeds','breast-cancer','Omniglot','bbc_news','20NewsGroups','biorxiv','big_patent']
    elif name in ['FashionMNIST','MNIST','seeds','breast-cancer','Omniglot','bbc_news','20NewsGroups_tfdif','biorxiv','big_patent']:
        edge_list, label=data_util.load_data(name,kchoice=10)
        n=len(label)
        vlist=[i for i in range(n)]
        label=data_util.set_labels(label)
        #print("Dataset names is ",name," |V|, |E| #clusters= ",n,len(edge_list),len(set(label)))


    #These are data of 4 popular directed graphs. 
    elif name in ['Cora','Cora full','Citeseer','Eu core']:
        edge_list,vlist,label,n,good_v=data_util.graph_database(name)
        label=data_util.set_labels(label)
        #print("Dataset names is ",name," |V|, |E| #clusters= ",n,len(edge_list),len(set(label)))
    
    G = nx.DiGraph(edge_list)
    return G, label

def write_out(data, name, max_nmi, max_purity):
    with open('./Results/'+data+'.txt', 'a') as f:
        f.write(name+'\n')
    with open('./Results/'+data+'.txt', 'a') as f:
        f.write('   Max NMI = [' + str(round(max_nmi[0],3)) + ',' + str(round(max_nmi[1],3)) + ']' + ' res:= ' + str(round(max_nmi[2],3)) + '\n')
    
    with open('./Results/'+data+'.txt', 'a') as f:
        f.write('   Partition sizes: [')
    for i in max_nmi[4]:
        #print(len(i),end=' ')
        with open('./Results/'+data+'.txt', 'a') as f:
            f.write(str(len(i))+', ')
    with open('./Results/'+data+'.txt', 'a') as f:
        f.write('] ' + '# of comm: ' + str(len(max_nmi[4]))+ '\n')
    
    
    with open('./Results/'+data+'.txt', 'a') as f:
        f.write('   Max Purity = [' + str(round(max_purity[0],3)) + ',' + str(round(max_purity[1],3)) + ']' + ' res:= ' + str(round(max_purity[2],3)) + '\n')
    with open('./Results/'+data+'.txt', 'a') as f:
        f.write('   Partition sizes: [')
    for i in max_purity[4]:
        with open('./Results/'+data+'.txt', 'a') as f:
            f.write(str(len(i))+', ')
    with open('./Results/'+data+'.txt', 'a') as f:
        f.write('] ' + '# of comm: ' + str(len(max_purity[4]))+ '\n')

###  Top K subgraph testing

In [60]:
import analysis as an
#import Cust_Final as RC10
import networkx.algorithms.community.louvain as Louv
from sklearn.metrics.cluster import normalized_mutual_info_score as NMI
from collections import deque

res_=[] #0.26, 0.24 is best for Louvain, 3.3, 2.0
labels=[]
total_labels=[]
names = []

data_names = ['Zhengmix8eq','mRNA','miRNA','FashionMNIST','MNIST','seeds','breast-cancer','Omniglot','bbc_news','20NewsGroups_tfdif','biorxiv','big_patent','Cora','Cora full','Citeseer','Eu core']
# FR_ord = ['Rd', 'Ord']
# FR_Recalc = ['FR_avg', 'FR_Re']
FR_tp = ['FL','FL_ng','FL_ng_prop','PageRank']
Num_hops = ['5','log(n)']
Mod_tp = {0: 'Louv'}

for data in data_names: 
    for survive in [0,1]:
        '''
        Get the Graph from Edge_List and get the labels
        '''
        #DO not recalculate Graph for non bulk RNA datasets
        if data not in ['mRNA','miRNA'] and survive==1:
            continue
        G, label= data_to_graph(data,survive)
        print('Number of nodes:',G.number_of_nodes())
        #get unique entry in label
        with open('./Results/'+data+'.txt', 'a') as f:
            f.write('True Labels: [')
            for i in list(set(label)):
                f.write(str(i)+', ')
            f.write('] # of Comms: ' + str(len(list(set(label))))+ '\n')

        for Num_hop in [0,1]:
            for FR_type in range(4):
                for Mod_type in [0]:
                    #skip survive for non bulk RNA datasets
                    if data not in ['mRNA','miRNA'] and survive==1:
                        continue
                    #Do pagerank once only (No different hops for PageRank)
                    if FR_type==3 and Num_hop==0:
                        continue

                    name =  data + ': '+ str(FR_tp[FR_type]) + ' + '+ str(Num_hops[Num_hop]) +' hops'
                    if FR_type==3:
                        name = data + ': PageRank'
                    if data in ['mRNA','miRNA']:
                        name = data + ': '+ str(FR_tp[FR_type]) + ' + '+ str(Num_hops[Num_hop]) +' hops' + ' + Survive: '+str(survive)
                        if FR_type==3:
                            name = data + ': PageRank' + ' + Survive: '+str(survive)
                    #print(name)
                    
                    
                    '''
                    Get induced subgraph of top k% nodes in FR value
                    '''
                    #Get induced subgraph
                    if Num_hop==0:
                        node2FR = calc_FlowRank(G, FR_type, 5)
                    else:
                        node2FR = calc_FlowRank(G, FR_type, np.log2(G.number_of_nodes()))
                    H = getInducedSubgraph(G, 0.2, node2FR)
                    #print('Number of nodes in subgraph:',H.number_of_nodes())

                    '''
                    Calculate NMI and Purity for different resolutions
                    '''
                    max_nmi = (0,0,0,0,[]) # (nmi, purity, res, FR_type, partition)
                    max_purity = (0,0,0,0,[])
                    res_list = []
                    for i in range(40):
                        res_list.append(i/20+0.01)
                    
                    for res in res_list:
                        #partition = RC10.louvain_partitions(H, seed=0,resolution=res,FR_order=FR_order, FR_Recalc=FR_Rec, FR_type=FR_type, Mod_type=Mod_type)
                        partition = Louv.louvain_partitions(H, seed=0,resolution=res)

                        partition_ = deque(partition, maxlen=1).pop()

                        nmi_ = get_NMI(H,partition_,label, G.number_of_nodes())
                        purity_ = get_Purity(H,partition_,label, G.number_of_nodes())
                        #print('NMI:', nmi_,'res:',res)
                        if nmi_>max_nmi[0]:
                            max_nmi = (nmi_,purity_,res,FR_type,partition_)
                        if purity_>max_purity[1]:
                            max_purity = (nmi_,purity_,res,FR_type,partition_)
                    '''
                    Write the results to Results folder
                    '''
                    write_out(data, name, max_nmi, max_purity)
                    #print(' Max NMI = [' , round(max_nmi[0],3), ',', round(max_nmi[1],3), ']', ' res:= ', round(max_nmi[2],3))
                    #print('Partition sizes:',end=' ')
                    # for i in max_nmi[4]:
                    #     print(len(i),end=' ')
                    # print()  
                    # 
                    #  #print(' Max Purity = [' , round(max_purity[0],3), ',', round(max_purity[1],3), ']', ' res:= ', round(max_purity[2],3))
                    # #print('Partition sizes:',end=' ')
                    # for i in max_purity[4]:
                    #    print(len(i),end=' ')
                    # print()  



Zhengmix8eq 3994
Log transform done
(3994, 50)
Accuracy of  15 -NN graph is 0.792
59910
Number of nodes: 3994
[0 1 2 3 4 5 6 7 8 9]
(11235, 19939)
selected vertices  11235
(11235,) Counter({'TCGA-BRCA': 1226, 'TCGA-KIRC': 610, 'TCGA-LUAD': 589, 'TCGA-UCEC': 585, 'TCGA-THCA': 572, 'TCGA-HNSC': 566, 'TCGA-PRAD': 554, 'TCGA-LUSC': 552, 'TCGA-LGG': 534, 'TCGA-COAD': 514, 'TCGA-SKCM': 473, 'TCGA-STAD': 448, 'TCGA-OV': 429, 'TCGA-BLCA': 428, 'TCGA-LIHC': 424, 'TCGA-KIRP': 323, 'TCGA-CESC': 309, 'TCGA-SARC': 265, 'TCGA-ESCA': 198, 'TCGA-PCPG': 187, 'TCGA-PAAD': 183, 'TCGA-READ': 177, 'TCGA-GBM': 174, 'TCGA-TGCT': 156, 'TCGA-LAML': 151, 'TCGA-THYM': 122, 'TCGA-KICH': 91, 'TCGA-MESO': 87, 'TCGA-UVM': 80, 'TCGA-ACC': 79, 'TCGA-UCS': 57, 'TCGA-DLBC': 48, 'TCGA-CHOL': 44})
33 32
Number of nodes: 11235
[ 5  6 10 11 12 14 16 17 25 26]
(9737, 19939)
selected vertices  9737
(9737,) Counter({0: 6980, 1: 2757})
2 1
Number of nodes: 9737
[0 1 2 3 4 5 6 7 8 9]
(11020, 1882)
selected vertices  11020
(11020

KeyboardInterrupt: 

## Louv + Cust-Louv on All Datasets

In [69]:
from collections import defaultdict, deque

def get_labels(partition,n_s):
    #final_partition_1 = deque(partition, maxlen=1).pop()
    #print(final_partition_1)


    label_1=np.zeros((n_s))
    c=0
    for sets in partition:
        for ell in sets:
            label_1[ell]=c
        
        c=c+1

    return label_1

In [74]:
import analysis as an
import Cust_Final as RC
#import networkx.algorithms.community.louvain as Louv
from sklearn.metrics.cluster import normalized_mutual_info_score as NMI
from collections import deque

res_=[] #0.26, 0.24 is best for Louvain, 3.3, 2.0
labels=[]
total_labels=[]
names = []

#data_names = ['Zhengmix8eq','mRNA','miRNA','FashionMNIST','MNIST','seeds','breast-cancer','Omniglot','bbc_news','20NewsGroups_tfdif','biorxiv','big_patent','Cora','Cora full','Citeseer','Eu core']
data_names = ['miRNA','FashionMNIST','MNIST','seeds','breast-cancer','Omniglot','bbc_news','20NewsGroups_tfdif','biorxiv','big_patent','Cora','Cora full','Citeseer','Eu core']
# FR_ord = ['Rd', 'Ord']
# FR_Recalc = ['FR_avg', 'FR_Re']
FR_ord = ['Rd', 'Ord']
FR_Recalc = ['FR_avg', 'FR_Re']
FR_tp = ['FL','FL_ng','FL_ng_prop','PageRank']
Mod_tp = {0:'Louv', 2:'Cust2', 6:'Cust6', 11:'Cust11'}


for data in data_names: 
    for survive in [0]:
    #for survive in [0,1]:
        '''
        Get the Graph from Edge_List and get the labels
        '''
        #DO not recalculate Graph for non bulk RNA datasets
        if data not in ['mRNA','miRNA'] and survive==1:
            continue
        G, label= data_to_graph(data,survive)
        print('Number of nodes:',G.number_of_nodes())
        #get unique entry in label
        with open('./Results/'+data+'.txt', 'a') as f:
            f.write('True Labels: [')
            for i in list(set(label)):
                f.write(str(i)+', ')
            f.write('] # of Comms: ' + str(len(list(set(label))))+ '\n')

        
        for FR_type in range(4):
            for FR_order in [0]:
                for FR_Rec in [0]:
                    for Mod_type in [0,2,6,11]:
                        #skip survive for non bulk RNA datasets
                        if data not in ['mRNA','miRNA'] and survive==1:
                            continue
                        
                        name =  data + '(All nodes): '+ str(FR_tp[FR_type]) + ' + '+ str(Mod_tp[Mod_type])
                        if FR_type==3:
                            name = data + ' (All nodes): PageRank' + ' + '+ str(Mod_tp[Mod_type])
                        if data in ['mRNA','miRNA']:
                            name = data + ' (All nodes): '+ str(FR_tp[FR_type]) + ' + '+ str(Mod_tp[Mod_type]) + ' + Survive: '+str(survive)
                            if FR_type==3:
                                name = data + ' (All nodes): PageRank' + ' + '+ str(Mod_tp[Mod_type]) + ' + Survive: '+str(survive)
                        #print(name)
                        
                        #Louvain doesn't have FlowRank values involved
                        if Mod_type==0:
                            name = data + ' (All nodes): '+ str(Mod_tp[Mod_type])
                        #Louvain just runs once
                        if Mod_type==0:
                            if FR_type!=0:
                                continue
                        #print('Number of nodes in subgraph:',H.number_of_nodes())

                        '''
                        Calculate NMI and Purity for different resolutions
                        '''
                        max_nmi = (0,0,0,0,[]) # (nmi, purity, res, FR_type, partition)
                        max_purity = (0,0,0,0,[])
                        res_list = []
                        for i in range(20):
                            res_list.append(i/10+0.01)
                        
                        for res in res_list:
                            partition = RC.louvain_partitions(G, seed=0,resolution=res,FR_order=FR_order, FR_Recalc=FR_Rec, FR_type=FR_type, Mod_type=Mod_type)
                            
                            partition_ = deque(partition, maxlen=1).pop()
                            label_new = get_labels(partition_,G.number_of_nodes())

                            nmi_ = NMI(label,label_new)
                            purity_ = met.purity_score(label,label_new)
                            #print('NMI:', nmi_,'res:',res)
                            if nmi_>max_nmi[0]:
                                max_nmi = (nmi_,purity_,res,FR_type,partition_)
                            if purity_>max_purity[1]:
                                max_purity = (nmi_,purity_,res,FR_type,partition_)
                        '''
                        Write the results to Results folder
                        '''
                        print ('Max NMI: ',max_nmi[0], 'at res: ',max_nmi[2])
                        write_out(data, name, max_nmi, max_purity)
                        #print(' Max NMI = [' , round(max_nmi[0],3), ',', round(max_nmi[1],3), ']', ' res:= ', round(max_nmi[2],3))
                        #print('Partition sizes:',end=' ')
                        # for i in max_nmi[4]:
                        #     print(len(i),end=' ')
                        # print()  
                        # 
                        #  #print(' Max Purity = [' , round(max_purity[0],3), ',', round(max_purity[1],3), ']', ' res:= ', round(max_purity[2],3))
                        # #print('Partition sizes:',end=' ')
                        # for i in max_purity[4]:
                        #    print(len(i),end=' ')
                        # print()  



[0 1 2 3 4 5 6 7 8 9]
(11020, 1882)
selected vertices  11020
(11020,) Counter({'TCGA-BRCA': 1202, 'TCGA-KIRC': 592, 'TCGA-UCEC': 575, 'TCGA-THCA': 573, 'TCGA-HNSC': 569, 'TCGA-LUAD': 564, 'TCGA-PRAD': 551, 'TCGA-LGG': 530, 'TCGA-LUSC': 523, 'TCGA-OV': 498, 'TCGA-STAD': 477, 'TCGA-COAD': 461, 'TCGA-SKCM': 452, 'TCGA-BLCA': 432, 'TCGA-LIHC': 425, 'TCGA-KIRP': 326, 'TCGA-CESC': 312, 'TCGA-SARC': 263, 'TCGA-ESCA': 198, 'TCGA-LAML': 188, 'TCGA-PCPG': 187, 'TCGA-PAAD': 183, 'TCGA-READ': 165, 'TCGA-TGCT': 156, 'TCGA-THYM': 126, 'TCGA-KICH': 91, 'TCGA-MESO': 87, 'TCGA-UVM': 80, 'TCGA-ACC': 80, 'TCGA-UCS': 57, 'TCGA-DLBC': 47, 'TCGA-CHOL': 45, 'TCGA-GBM': 5})
33 32
Number of nodes: 11020
Max NMI:  0.8354813887877923 at res:  0.61
Max NMI:  0.8185235033396749 at res:  1.81
Max NMI:  0.8342545951244514 at res:  1.81
Max NMI:  0.838109425507587 at res:  1.01
Max NMI:  0.834690943637039 at res:  1.61
Max NMI:  0.8342885942625952 at res:  1.31
Max NMI:  0.8389953858482124 at res:  0.71
Max NMI:  0.8

C:\Users\MSI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scipy\sparse\_index.py:145: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


20 19
Number of nodes: 10909
Max NMI:  0.3365657118992977 at res:  1.91
Max NMI:  0.31730292551202643 at res:  1.81
Max NMI:  0.32002212735943963 at res:  1.91
Max NMI:  0.34182464951250596 at res:  1.91
Max NMI:  0.31955380714913795 at res:  1.81
Max NMI:  0.32258372115961387 at res:  1.91
Max NMI:  0.3439614162920427 at res:  1.91
Max NMI:  0.3229099077110389 at res:  1.51
Max NMI:  0.32819282454277704 at res:  1.91
Max NMI:  0.34096090096663195 at res:  1.91
Max NMI:  0.3426365319321868 at res:  1.91
Max NMI:  0.3385641133377422 at res:  1.91
Max NMI:  0.3402687193975797 at res:  1.91
biorxiv (68131, 50)
26 25
Number of nodes: 68131
Max NMI:  0.36170559657257567 at res:  1.81
Max NMI:  0.32608523686253266 at res:  1.81
Max NMI:  0.3409331462154175 at res:  1.51
Max NMI:  0.365511733997418 at res:  1.61
Max NMI:  0.3600729786772639 at res:  1.91
Max NMI:  0.3614542689499371 at res:  1.71
Max NMI:  0.36294932552347997 at res:  1.51
Max NMI:  0.362175457173279 at res:  1.41
Max NMI:  0

TypeError: invalid operation on untyped list